// data.js
// 60 realistic Indian tech jobs. Global variable JOBS is available to app.js.
const JOBS = [
    {
      id: "job-001",
      title: "SDE Intern",
      company: "Infosys",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "Data Structures", "SQL"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://careers.infosys.com/apply/job-001",
      description: "Join a foundational engineering team building backend services. Work closely with senior engineers and participate in code reviews. Ideal for strong CS fundamentals and eagerness to learn."
    },
    {
      id: "job-002",
      title: "Graduate Engineer Trainee",
      company: "TCS",
      location: "Mumbai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "REST", "Agile"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "3–5 LPA",
      applyUrl: "https://careers.tcs.com/job-002",
      description: "Entry-level role building enterprise Java applications. Expect collaborative sprints and structured mentorship. Strong problem-solving and good communication are required."
    },
    {
      id: "job-003",
      title: "Junior Backend Developer",
      company: "Wipro",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Node.js", "Express", "MongoDB"],
      source: "Indeed",
      postedDaysAgo: 4,
      salaryRange: "6–10 LPA",
      applyUrl: "https://wipro.referrals/jobs/job-003",
      description: "Contribute to building scalable microservices. Work with product teams to ship features and monitor performance. Good foundation in JS runtime and asynchronous patterns preferred."
    },
    {
      id: "job-004",
      title: "Frontend Intern",
      company: "Accenture",
      location: "Pune",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["HTML", "CSS", "JavaScript", "React"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://accenture.taleo.net/careersection/job-004",
      description: "Hands-on internship building UI components with React. Work closely with designers to translate designs into accessible interfaces. Ideal for students with web fundamentals."
    },
    {
      id: "job-005",
      title: "QA Intern",
      company: "Capgemini",
      location: "Gurgaon",
      mode: "Hybrid",
      experience: "Fresher",
      skills: ["Manual Testing", "Test Cases", "Selenium (basic)"],
      source: "Naukri",
      postedDaysAgo: 3,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://capgemini.jobs/apply/job-005",
      description: "Support QA cycles and create reproducible test cases. Collaborate with engineering to ensure release quality. Basic scripting knowledge is a plus."
    },
    {
      id: "job-006",
      title: "Data Analyst Intern",
      company: "Cognizant",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Excel", "SQL", "Power BI"],
      source: "Indeed",
      postedDaysAgo: 6,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://cognizant.com/careers/job-006",
      description: "Assist teams with data preparation and basic analysis. Produce dashboards and insights for operational stakeholders. Ideal for analytical graduates comfortable with spreadsheets and SQL."
    },
    {
      id: "job-007",
      title: "Java Developer (0-1)",
      company: "IBM",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Java", "Spring Boot", "SQL"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "6–10 LPA",
      applyUrl: "https://ibm.com/jobs/job-007",
      description: "Work on enterprise services using Java and Spring Boot. Collaborate with cross-functional teams to deliver stable services. Strong coding discipline is expected."
    },
    {
      id: "job-008",
      title: "Python Developer (Fresher)",
      company: "Oracle",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Python", "APIs", "Unit Testing"],
      source: "Naukri",
      postedDaysAgo: 5,
      salaryRange: "6–10 LPA",
      applyUrl: "https://oracle.com/careers/job-008",
      description: "Develop backend endpoints and internal tooling in Python. Learn from experienced engineers and contribute to production-grade services. Focus on testability and maintainability."
    },
    {
      id: "job-009",
      title: "React Developer (1-3)",
      company: "SAP",
      location: "Pune",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "TypeScript", "CSS Modules"],
      source: "Indeed",
      postedDaysAgo: 7,
      salaryRange: "10–18 LPA",
      applyUrl: "https://sap.com/jobs/job-009",
      description: "Build customer-facing dashboards with React and TypeScript. Emphasis on performance and accessibility. Experience with testing and CI is helpful."
    },
    {
      id: "job-010",
      title: "Junior Backend Developer",
      company: "Dell",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Go", "Microservices", "gRPC"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "6–10 LPA",
      applyUrl: "https://jobs.dell.com/job-010",
      description: "Contribute to cloud-native backend services. Participate in design discussions and own small features. Familiarity with Go and RPC frameworks is a plus."
    },
    {
      id: "job-011",
      title: "SDE Intern",
      company: "Amazon",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "Distributed Systems", "Algorithms"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://amazon.jobs/job-011",
      description: "Intern role on a high-scale team building resilient services. Work on real customer problems and ship production quality code. Strong algorithmic skills required."
    },
    {
      id: "job-012",
      title: "Frontend Intern",
      company: "Flipkart",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["React", "HTML", "CSS"],
      source: "Naukri",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://flipkartcareers.com/job-012",
      description: "Build and optimize components for a large consumer-facing application. Collaborate with product and design. A strong eye for UI detail is beneficial."
    },
    {
      id: "job-013",
      title: "Junior Backend Developer",
      company: "Swiggy",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Python", "Django", "Postgres"],
      source: "Indeed",
      postedDaysAgo: 2,
      salaryRange: "10–18 LPA",
      applyUrl: "https://careers.swiggy.com/job-013",
      description: "Join a fast-paced payments integration team. Build reliable backend services and improve service observability. Comfort with relational databases is needed."
    },
    {
      id: "job-014",
      title: "QA Intern",
      company: "Razorpay",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Manual Testing", "Basic Automation", "APIs"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://razorpay.com/careers/job-014",
      description: "Support QA across product releases, writing test cases and reporting bugs. Learn automation basics and API testing. Strong attention to detail required."
    },
    {
      id: "job-015",
      title: "Python Developer (1-3)",
      company: "PhonePe",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Python", "Kafka", "SQL"],
      source: "Naukri",
      postedDaysAgo: 6,
      salaryRange: "10–18 LPA",
      applyUrl: "https://phonepe.com/careers/job-015",
      description: "Build backend components for payment flows. Work on event-driven architectures and ensure data correctness. Experience with messaging systems is preferred."
    },
    {
      id: "job-016",
      title: "Data Analyst Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["SQL", "Excel", "Data Viz"],
      source: "Indeed",
      postedDaysAgo: 0,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://zoho.com/jobs/job-016",
      description: "Support product teams with reporting and KPIs. Create concise dashboards and surface insights. Ideal for detail-oriented candidates."
    },
    {
      id: "job-017",
      title: "React Developer (1-3)",
      company: "Freshworks",
      location: "Chennai",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "Redux", "TypeScript"],
      source: "LinkedIn",
      postedDaysAgo: 8,
      salaryRange: "10–18 LPA",
      applyUrl: "https://freshworks.com/careers/job-017",
      description: "Work on a SaaS-first frontend with React and TypeScript. Focus on quality and predictable state management. Experience writing component tests is beneficial."
    },
    {
      id: "job-018",
      title: "Java Developer (1-3)",
      company: "Juspay",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "1-3",
      skills: ["Java", "Payments", "Spring"],
      source: "Naukri",
      postedDaysAgo: 5,
      salaryRange: "10–18 LPA",
      applyUrl: "https://juspay.in/jobs/job-018",
      description: "Contribute to payment gateway integrations. Build robust APIs and improve latency. Prior payments domain exposure helpful but not required."
    },
    {
      id: "job-019",
      title: "Junior Backend Developer",
      company: "CRED",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Kotlin", "REST", "Postgres"],
      source: "Indeed",
      postedDaysAgo: 7,
      salaryRange: "10–18 LPA",
      applyUrl: "https://cred.club/careers/job-019",
      description: "Join backend teams working on customer-facing services. Learn production-grade Kotlin service patterns and testing. Strong debugging skills recommended."
    },
    {
      id: "job-020",
      title: "SDE Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["JavaScript", "Node.js", "APIs"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://zoho.com/careers/job-020",
      description: "Intern on a small product team building backend APIs. Expect mentoring, code reviews, and practical exposure to production systems. Great for early-career engineers."
    },
    {
      id: "job-021",
      title: "Frontend Intern",
      company: "Freshworks",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["HTML", "CSS", "React"],
      source: "Indeed",
      postedDaysAgo: 9,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://freshworks.com/jobs/job-021",
      description: "Work with UX teams to implement pixel-accurate components. Gain production experience and mentorship. A portfolio of projects is useful."
    },
    {
      id: "job-022",
      title: "Junior Backend Developer",
      company: "PhonePe",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Java", "Microservices", "Docker"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "10–18 LPA",
      applyUrl: "https://phonepe.com/job-022",
      description: "Build services focusing on resiliency and deployment. Work with containerized stacks and CI pipelines. Good testing habits expected."
    },
    {
      id: "job-023",
      title: "Data Analyst Intern",
      company: "Amazon",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["SQL", "Python", "Excel"],
      source: "Naukri",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://amazon.jobs/job-023",
      description: "Support large-scale data analysis for product metrics. Build reproducible notebooks and collaborate with PMs. Strong SQL skills required."
    },
    {
      id: "job-024",
      title: "Python Developer (0-1)",
      company: "Flipkart",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Python", "Django", "APIs"],
      source: "LinkedIn",
      postedDaysAgo: 4,
      salaryRange: "6–10 LPA",
      applyUrl: "https://flipkartcareers.com/job-024",
      description: "Contribute to backend services supporting large catalogs. Focus on clean code and performance. Mentor support available for domain knowledge."
    },
    {
      id: "job-025",
      title: "Junior Backend Developer",
      company: "Razorpay",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Go", "Postgres", "Docker"],
      source: "Indeed",
      postedDaysAgo: 6,
      salaryRange: "10–18 LPA",
      applyUrl: "https://razorpay.com/jobs/job-025",
      description: "Work on payment orchestration services with a focus on reliability. Participate in on-call rotations and improve system metrics. Previous backend experience helpful."
    },
    {
      id: "job-026",
      title: "React Developer (1-3)",
      company: "Swiggy",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "Redux", "Testing Library"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "10–18 LPA",
      applyUrl: "https://swiggy.com/careers/job-026",
      description: "Build and refine interactive web experiences for large user bases. Emphasis on robust client-side state and test coverage. Familiarity with performance profiling helpful."
    },
    {
      id: "job-027",
      title: "SDE Intern",
      company: "Paytm",
      location: "Noida",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "SQL", "APIs"],
      source: "Naukri",
      postedDaysAgo: 3,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://paytm.com/careers/job-027",
      description: "Intern on core engineering teams developing payment flows. Expect real ownership and learning. Good debugging skills and curiosity preferred."
    },
    {
      id: "job-028",
      title: "Frontend Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["JavaScript", "CSS", "Accessibility"],
      source: "Indeed",
      postedDaysAgo: 5,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://zoho.com/jobs/job-028",
      description: "Implement accessible and responsive UI components. Work with designers and engineers to ship small features. Ideal for disciplined front-end interns."
    },
    {
      id: "job-029",
      title: "Java Developer (1-3)",
      company: "Cognizant",
      location: "Pune",
      mode: "Onsite",
      experience: "1-3",
      skills: ["Java", "Spring", "Microservices"],
      source: "LinkedIn",
      postedDaysAgo: 8,
      salaryRange: "6–10 LPA",
      applyUrl: "https://cognizant.com/jobs/job-029",
      description: "Deliver Java microservices for enterprise customers. Participate in code reviews and system design sessions. Stability and clarity of code prioritized."
    },
    {
      id: "job-030",
      title: "Junior Backend Developer",
      company: "Infosys",
      location: "Mysuru",
      mode: "Onsite",
      experience: "0-1",
      skills: ["C#", ".NET", "SQL Server"],
      source: "Naukri",
      postedDaysAgo: 2,
      salaryRange: "6–10 LPA",
      applyUrl: "https://careers.infosys.com/job-030",
      description: "Work on enterprise .NET applications with structured delivery cycles. Strong discipline and willingness to learn required. Mentorship provided."
    },
    {
      id: "job-031",
      title: "Data Analyst Intern",
      company: "Amazon",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["SQL", "Python", "Tableau"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://amazon.jobs/job-031",
      description: "Assist with data pipelines and produce insights for business stakeholders. Work on scalable workflows and reproducible analysis. Strong SQL proficiency is expected."
    },
    {
      id: "job-032",
      title: "React Developer (1-3)",
      company: "Flipkart",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "Next.js", "TypeScript"],
      source: "Indeed",
      postedDaysAgo: 4,
      salaryRange: "10–18 LPA",
      applyUrl: "https://flipkartcareers.com/job-032",
      description: "Build SSR-enabled customer experiences using Next.js. Focus on accessibility, performance and robustness. Experience with TypeScript required."
    },
    {
      id: "job-033",
      title: "SDE Intern",
      company: "Dell",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["C++", "Systems", "Debugging"],
      source: "Naukri",
      postedDaysAgo: 6,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://jobs.dell.com/job-033",
      description: "Systems-focused internship with mentorship on performance and low-level debugging. Ideal for students with strong CS basics and curiosity about systems internals."
    },
    {
      id: "job-034",
      title: "Junior Backend Developer",
      company: "Accenture",
      location: "Gurgaon",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Node.js", "Express", "MongoDB"],
      source: "LinkedIn",
      postedDaysAgo: 7,
      salaryRange: "6–10 LPA",
      applyUrl: "https://accenture.taleo.net/careersection/job-034",
      description: "Work on cloud-native services with REST APIs. Desire to learn and collaborate across teams is important. Opportunity to gain enterprise software experience."
    },
    {
      id: "job-035",
      title: "QA Intern",
      company: "IBM",
      location: "Pune",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Manual Testing", "Test Reporting"],
      source: "Indeed",
      postedDaysAgo: 3,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://ibm.com/jobs/job-035",
      description: "Support formal QA processes and track release quality. Work with test plans and automation leads. Good communication and attention to detail required."
    },
    {
      id: "job-036",
      title: "Python Developer (1-3)",
      company: "Oracle",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Python", "Flask", "SQL"],
      source: "Naukri",
      postedDaysAgo: 5,
      salaryRange: "10–18 LPA",
      applyUrl: "https://oracle.com/careers/job-036",
      description: "Build REST APIs and internal tooling. Work on readable, well-tested code and shipping features iteratively. Familiarity with CI pipelines helpful."
    },
    {
      id: "job-037",
      title: "Junior Backend Developer",
      company: "Capgemini",
      location: "Mumbai",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "SQL", "APIs"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "6–10 LPA",
      applyUrl: "https://capgemini.jobs/job-037",
      description: "Develop and maintain backend services for enterprise customers. Join agile teams and contribute to design discussions. Clear coding practices are valued."
    },
    {
      id: "job-038",
      title: "React Developer (1-3)",
      company: "Zoho",
      location: "Chennai",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "CSS-in-JS", "Accessibility"],
      source: "Indeed",
      postedDaysAgo: 9,
      salaryRange: "10–18 LPA",
      applyUrl: "https://zoho.com/careers/job-038",
      description: "Work on customer-facing SaaS modules focusing on accessibility and performance. Strong component design skills and testing discipline are expected."
    },
    {
      id: "job-039",
      title: "SDE Intern",
      company: "CRED",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Kotlin", "Android", "APIs"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://cred.club/careers/job-039",
      description: "Mobile-focused internship building Android features and services. Collaborate with backend teams and focus on robust offline-first behavior. Good Kotlin basics required."
    },
    {
      id: "job-040",
      title: "Junior Backend Developer",
      company: "Juspay",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "Payments", "MySQL"],
      source: "Naukri",
      postedDaysAgo: 4,
      salaryRange: "6–10 LPA",
      applyUrl: "https://juspay.in/jobs/job-040",
      description: "Join payment integration efforts, building stable transactional services. Learn from experienced engineers and participate in deployments. Reliability-focused mindset helps."
    },
    {
      id: "job-041",
      title: "Frontend Intern",
      company: "Cognizant",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["HTML", "CSS", "JavaScript"],
      source: "Indeed",
      postedDaysAgo: 8,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://cognizant.com/careers/job-041",
      description: "Implement UI components and collaborate with UX designers. Gain experience with large codebases and release processes. Good communication helps."
    },
    {
      id: "job-042",
      title: "Data Analyst Intern",
      company: "Freshworks",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["SQL", "Python", "BI Tools"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://freshworks.com/jobs/job-042",
      description: "Create reports and dashboards supporting product metrics. Work with cross-functional teams and present insights. Strong data curiosity is central to the role."
    },
    {
      id: "job-043",
      title: "Java Developer (0-1)",
      company: "IBM",
      location: "Pune",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Java", "Spring", "SQL"],
      source: "Naukri",
      postedDaysAgo: 6,
      salaryRange: "6–10 LPA",
      applyUrl: "https://ibm.com/jobs/job-043",
      description: "Develop Java services for enterprise workloads. Learn design patterns and test-driven development. Team-oriented environment and mentorship are provided."
    },
    {
      id: "job-044",
      title: "React Developer (1-3)",
      company: "Amazon",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "1-3",
      skills: ["React", "Redux", "Performance"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "10–18 LPA",
      applyUrl: "https://amazon.jobs/job-044",
      description: "Work on consumer-facing frontend features with high performance demands. Strong understanding of rendering and runtime costs expected. Collaborate with cross-functional teams daily."
    },
    {
      id: "job-045",
      title: "Junior Backend Developer",
      company: "TCS",
      location: "Mumbai",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "SOAP/REST", "Oracle DB"],
      source: "Indeed",
      postedDaysAgo: 3,
      salaryRange: "6–10 LPA",
      applyUrl: "https://tcs.com/careers/job-045",
      description: "Work in client-facing projects building integration layers. Structured delivery model and clear expectations. Strong testing and documentation skills valued."
    },
    {
      id: "job-046",
      title: "SDE Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["PHP", "MySQL", "Web Services"],
      source: "Naukri",
      postedDaysAgo: 7,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://zoho.com/jobs/job-046",
      description: "Internship focusing on web backend and database interactions. Pair with mentors and contribute to product features. Good SQL understanding is important."
    },
    {
      id: "job-047",
      title: "Python Developer (1-3)",
      company: "Oracle",
      location: "Hyderabad",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Python", "Celery", "Postgres"],
      source: "LinkedIn",
      postedDaysAgo: 9,
      salaryRange: "10–18 LPA",
      applyUrl: "https://oracle.com/jobs/job-047",
      description: "Build background processing pipelines and APIs. Focus on reliability and monitoring. Strong testing practices are a plus."
    },
    {
      id: "job-048",
      title: "Junior Backend Developer",
      company: "Dell",
      location: "Pune",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "Microservices", "Kubernetes"],
      source: "Indeed",
      postedDaysAgo: 5,
      salaryRange: "6–10 LPA",
      applyUrl: "https://jobs.dell.com/job-048",
      description: "Join backend teams shipping containerized services. Work on CI/CD pipelines and observability. Mentors available to guide you through production practices."
    },
    {
      id: "job-049",
      title: "React Developer (1-3)",
      company: "Flipkart",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "Performance", "GraphQL"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "10–18 LPA",
      applyUrl: "https://flipkartcareers.com/job-049",
      description: "Build interactive, high-performance UIs for commerce flows. Work closely with backend teams to design lightweight APIs. Attention to UX and metrics is expected."
    },
    {
      id: "job-050",
      title: "Junior Backend Developer",
      company: "Accenture",
      location: "Gurgaon",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["C#", ".NET", "SQL"],
      source: "Naukri",
      postedDaysAgo: 0,
      salaryRange: "6–10 LPA",
      applyUrl: "https://accenture.taleo.net/careersection/job-050",
      description: "Develop enterprise .NET solutions with a focus on maintainable code. Participate in code reviews and team design sessions. Strong collaboration skills are important."
    },
    {
      id: "job-051",
      title: "Data Analyst Intern",
      company: "Swiggy",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["SQL", "Python", "Looker"],
      source: "Indeed",
      postedDaysAgo: 6,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://swiggy.com/jobs/job-051",
      description: "Support operational analytics and build dashboards. Work with stakeholders to turn data into action. Comfortable writing SQL and simple analysis scripts."
    },
    {
      id: "job-052",
      title: "Junior Backend Developer",
      company: "PhonePe",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "Spring Boot", "Redis"],
      source: "LinkedIn",
      postedDaysAgo: 3,
      salaryRange: "6–10 LPA",
      applyUrl: "https://phonepe.com/careers/job-052",
      description: "Implement backend features and improve caching layers. Work within a small squad and deliver production changes. Clear unit testing expectations."
    },
    {
      id: "job-053",
      title: "React Developer (1-3)",
      company: "Freshworks",
      location: "Chennai",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["React", "Storybook", "TypeScript"],
      source: "Naukri",
      postedDaysAgo: 8,
      salaryRange: "10–18 LPA",
      applyUrl: "https://freshworks.com/careers/job-053",
      description: "Build reusable components and maintain a component library. Work with designers to ensure consistency and accessibility. Strong TypeScript familiarity preferred."
    },
    {
      id: "job-054",
      title: "SDE Intern",
      company: "Juspay",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["Java", "Payments", "APIs"],
      source: "LinkedIn",
      postedDaysAgo: 2,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://juspay.in/jobs/job-054",
      description: "Intern on critical payment rails, learning scalable design patterns. Contribute to production code with guidance from seniors. Strong problem-solving aptitude required."
    },
    {
      id: "job-055",
      title: "Frontend Intern",
      company: "CRED",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["React", "UI", "CSS"],
      source: "Indeed",
      postedDaysAgo: 5,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://cred.club/careers/job-055",
      description: "Work with frontend teams building polished interfaces. Learn component-driven development and testing practices. Portfolio projects are beneficial."
    },
    {
      id: "job-056",
      title: "Python Developer (1-3)",
      company: "Razorpay",
      location: "Bengaluru",
      mode: "Hybrid",
      experience: "1-3",
      skills: ["Python", "Redis", "APIs"],
      source: "LinkedIn",
      postedDaysAgo: 0,
      salaryRange: "10–18 LPA",
      applyUrl: "https://razorpay.com/careers/job-056",
      description: "Work on transaction processing and backend reliability. Focus on observability and fault tolerance. Good testing and debugging practices required."
    },
    {
      id: "job-057",
      title: "Junior Backend Developer",
      company: "Infosys",
      location: "Bengaluru",
      mode: "Onsite",
      experience: "0-1",
      skills: ["Java", "REST", "SQL"],
      source: "Naukri",
      postedDaysAgo: 9,
      salaryRange: "6–10 LPA",
      applyUrl: "https://careers.infosys.com/job-057",
      description: "Participate in client projects building REST services. Learn testing, CI and deployment basics. Mentorship and formal training included."
    },
    {
      id: "job-058",
      title: "Data Analyst Intern",
      company: "Zoho",
      location: "Chennai",
      mode: "Onsite",
      experience: "Fresher",
      skills: ["SQL", "R", "Data Viz"],
      source: "Indeed",
      postedDaysAgo: 4,
      salaryRange: "₹15k–₹40k/month Internship",
      applyUrl: "https://zoho.com/jobs/job-058",
      description: "Create reproducible analyses and visualizations supporting product decisions. Collaborate with product managers to deliver insights. Analytical curiosity is key."
    },
    {
      id: "job-059",
      title: "React Developer (1-3)",
      company: "Amazon",
      location: "Hyderabad",
      mode: "Onsite",
      experience: "1-3",
      skills: ["React", "TypeScript", "GraphQL"],
      source: "LinkedIn",
      postedDaysAgo: 1,
      salaryRange: "10–18 LPA",
      applyUrl: "https://amazon.jobs/job-059",
      description: "Design and implement front-end modules on a large-scale platform. Emphasize type-safety and maintainable patterns. Strong collaborative skills required."
    },
    {
      id: "job-060",
      title: "Junior Backend Developer",
      company: "Capgemini",
      location: "Mumbai",
      mode: "Hybrid",
      experience: "0-1",
      skills: ["Node.js", "Postgres", "Docker"],
      source: "Naukri",
      postedDaysAgo: 10,
      salaryRange: "6–10 LPA",
      applyUrl: "https://capgemini.jobs/apply/job-060",
      description: "Develop REST services and collaborate with testing teams. Learn infrastructure and deployment basics. Good communication and willingness to learn expected."
    }
  ];
  
  // Expose globally for app.js
  window.JOBS = JOBS;